# Generated by Django 6.0.2 on 2026-02-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('release_date', models.DateField(db_index=True)),
                ('rating', models.FloatField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.language')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'rating'], name='movies_movi_languag_e89490_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx')],
            },
        ),
    ]
