# Generated by Django 6.0.2 on 2026-02-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_release_b7ac7d_idx',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'release_date'], name='movies_movi_languag_2ba94a_idx'),
        ),
    ]
