# Generated by Django 6.0.2 on 2026-02-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_movies_movi_release_b7ac7d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(db_index=True, related_name='movies', to='movies.genre'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
    ]
