# Generated by Django 6.0.2 on 2026-02-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('show_time', models.DateTimeField(db_index=True)),
                ('seat_numbers', models.CharField(max_length=100)),
                ('payment_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['user_email', 'created_at'], name='movies_book_user_em_a6275c_idx'), models.Index(fields=['movie', 'show_time'], name='movies_book_movie_i_5d7756_idx')],
            },
        ),
    ]
