# Generated by Django 6.0.2 on 2026-03-04 10:59

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_genres_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, validators=[movies.models.validate_youtube_url]),
        ),
    ]
