# Generated by Django 6.0.2 on 2026-03-10 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_paymentwebhookevent_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
