# Generated by Django 6.0.2 on 2026-03-10 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_booking_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
